interceptors:
  - name: MongoDB
    config:
      url: mongodb://localhost:27017
services:
  com.example.ExampleService:
    endpoints:
      ListTestMovies:
        database: test
        collection: movies
        options: 'options.FindOptions {Limit: req.limit}'
        paginatedfind:
          filter: '{}'
          cursor: 'req.cursor'
      GetTestMovies:
        database: test
        collection: movies
        mapresponse: '{ "data": resp }'
        findone:
          filter: '{ "_id": ObjectID(req._id) }'
      CreateTestMovies:
        database: test
        collection: movies
        insertone:
          document: '{ ?"awards": req.?data.?awards, ?"cast": req.?data.?cast, ?"countries": req.?data.?countries, ?"directors": req.?data.?directors, ?"fullplot": req.?data.?fullplot, ?"genres": req.?data.?genres, ?"imdb": req.?data.?imdb, ?"languages": req.?data.?languages, ?"lastupdated": req.?data.?lastupdated, ?"metacritic": req.?data.?metacritic, ?"num_mflix_comments": req.?data.?num_mflix_comments, ?"plot": req.?data.?plot, ?"poster": req.?data.?poster, ?"rated": req.?data.?rated, ?"released": req.?data.?released, ?"runtime": req.?data.?runtime, ?"title": req.?data.?title, ?"tomatoes": req.?data.?tomatoes, ?"type": req.?data.?type, ?"writers": req.?data.?writers, ?"year": req.?data.?year}'
      UpdateTestMovies:
        database: test
        collection: movies
        replaceone:
          filter: '{ "_id": ObjectID(req.data._id) }'
          replacement: '{ ?"awards": req.?data.?awards, ?"cast": req.?data.?cast, ?"countries": req.?data.?countries, ?"directors": req.?data.?directors, ?"fullplot": req.?data.?fullplot, ?"genres": req.?data.?genres, ?"imdb": req.?data.?imdb, ?"languages": req.?data.?languages, ?"lastupdated": req.?data.?lastupdated, ?"metacritic": req.?data.?metacritic, ?"num_mflix_comments": req.?data.?num_mflix_comments, ?"plot": req.?data.?plot, ?"poster": req.?data.?poster, ?"rated": req.?data.?rated, ?"released": req.?data.?released, ?"runtime": req.?data.?runtime, ?"title": req.?data.?title, ?"tomatoes": req.?data.?tomatoes, ?"type": req.?data.?type, ?"writers": req.?data.?writers, ?"year": req.?data.?year}'
      DeleteTestMovies:
        database: test
        collection: movies
        deleteone:
          filter: '{ "_id": ObjectID(req._id) }'
